### ISSUE TITLE
Shearing with Dispenser doesn't multiply drops

### ISSUE THREAD

**Issue by BBSnowIce** [OmerBenGera/WildStacker#11]
**Description of the issue**:
It seems that when a dispenser shears a stacked sheep, the entire stack is sheared but only the equivalent of one sheared sheep is dropped.

**Expected behaviour**:
The stack splits every time a sheep is sheared as it does when a player shears a stacked sheep.

**Comment by OmerBenGera** [comment]
Build #22 will fix the issue :)
