### ISSUE TITLE
MMOItems have incorrect names

### ISSUE THREAD

**Issue by ZeeRaider** [OmerBenGera/WildStacker#13]
Custom items created with MMOItems default to the base-item.
Such as if an item uses a player head as a base item - instead of using the assigned name given, it will show as "2 x Player Head".
Using the latest build.
Using latest Tuinity (essentially Paper)

**Comment by OmerBenGera** [comment]
Try enabling display-name under the items section

**Comment by ZeeRaider** [comment]
Sorry, I was actually just about to update this - I found the setting.
Many thanks for the reply all the same.
My issue is resolved.
