### ISSUE TITLE
Crash || IllegalStateException || 1.8.8

### ISSUE THREAD

**Issue by klaidoshka** [OmerBenGera/WildStacker#14]
Hello.

This has never happened before, only now. Something with WildStacker and Citizens I suppose.

Server version: Latest Paper 1.8.8
WildStacker version: 3.4.3 (dev version with slime bug fixes if I recall correctly)
Pastebin: https://pastebin.com/wzGCux1T

Is this WildStacker's problem or... ?

**Comment by OmerBenGera** [comment]
Something with Citizens's implemention not set up.
Delete Citizens and it will work or get it fixed with Citizens.
Also, update to latest version, might fix the issue

Closing this for now
