### ISSUE TITLE
Nameplates above stacked mobs don't show on server reboot

### ISSUE THREAD

**Issue by Gitberham** [OmerBenGera/WildStacker#15]
After rebooting the server, stacked mobs don't show their nameplates right away. An update to the stack (e.g. sheep being sheared or regrowing wool) will show the nameplates again.
This creates a lot of confusion.
![afbeelding](https://user-images.githubusercontent.com/76908688/104306070-caa87a80-54cd-11eb-9f7e-1c495e81afbc.png)

**Comment by OmerBenGera** [comment]
I can replicate the issue as well, gonna check that rn

**Comment by OmerBenGera** [comment]
Fixed in build #27
