### ISSUE TITLE
BukkitSchedule calls Optimization

### ISSUE THREAD

**Issue by BBSnowIce** [OmerBenGera/WildStacker#17]
**Description of the issue**:
WildStacker seems to be causing crashes on my server and Ome_R enjoined me to open this issue because it seems to be caused by serveral BukkitSchedule calls from WildStacker.

Here are some traces on server crash : https://pastebin.com/eGHj5u02

**Comment by OmerBenGera** [comment]
Hey, try latest build, should be better

**Comment by OmerBenGera** [comment]
@BBSnowIce Does it work?

**Comment by BBSnowIce** [comment]
I have to test it on a productive as I was not able to reproduce the issue on a test server, I'll send a message when done

**Comment by OmerBenGera** [comment]
@BBSnowIce Have you tried it?

**Comment by BBSnowIce** [comment]
Yes my colleagues activated it today morning and it seems to be fine with Mob stacking enabled. I'll reopen the issue if a similar problem appears, sorry for being so long.

**Comment by OmerBenGera** [comment]
Great :)
