### ISSUE TITLE
Wildstacker 3.5.1 - Issues with upgraded spawners spawning correct mobs. 

### ISSUE THREAD

**Issue by MythricHD** [OmerBenGera/WildStacker#18]
I've been playing around with the new spawner upgrades system and everything works very well except i found one bug. When a spawner stack only have 1 spawner then it does not spawn upgraded mobs and it seems like the mobs stop stacking. Once i have 2 or more spawners then it spawns the proper upgraded mob and stacks it. 

Here is what happens when there is only one spawner: https://i.imgur.com/9EaIp7e.png

Two or more (proper function): https://i.imgur.com/DtFkG5p.png

I also had a question if there could be a permission to use the manage spawner gui as i dont want certain players to beable to remove spawners without silk but maybe let certain ranks use the remove amounts gui. Maybe also the same thing to have a permission to use the upgrade menu. Just an idea. 

Thanks for your hard work Omer. This new update is the best WS has had

**Comment by OmerBenGera** [comment]
Show me your config please (upload it to pastebin)

**Comment by MythricHD** [comment]
> Show me your config please (upload it to pastebin)

https://paste.helpch.at/abuzukezir.bash This is my current config

**Comment by OmerBenGera** [comment]
Try using latest build, might fix it

**Comment by MythricHD** [comment]
https://i.imgur.com/muCFoKa.png Still spawning unique mobs that dont stack and does not have the upgrade.

**Comment by OmerBenGera** [comment]
> 
> 
> https://i.imgur.com/muCFoKa.png Still spawning unique mobs that dont stack and does not have the upgrade.
> 
> Also after restarts if a single spawner has an upgraded hologram above it, it disappears. Don't know if this could help at all but i figured id say it.

The spawner doesn't have an upgrade, as you can see from the inspect tool. I will try and replicate the issue and see what's going on by using your config

**Comment by OmerBenGera** [comment]
Fixed in build #34

**Comment by MythricHD** [comment]
Build 34 fixed a single upgraded spawner spawning default tiers. Only issue now is that it seems like single spawners do not save their upgrade after restart.

Here is a photo: https://i.imgur.com/VPF7zeY.png 
Before restart the spawner had the upgrade doubloon and a hologram ontop. After restart its hologram is gone and it is not default tier and spawns default mobs. 

This looks like the only issue now, thanks for trying to fix!

**Comment by OmerBenGera** [comment]
> 
> 
> Build 34 fixed a single upgraded spawner spawning default tiers. Only issue now is that it seems like single spawners do not save their upgrade after restart.
> 
> Here is a photo: https://i.imgur.com/VPF7zeY.png
> Before restart the spawner had the upgrade doubloon and a hologram ontop. After restart its hologram is gone and it is not default tier and spawns default mobs.
> 
> This looks like the only issue now, thanks for trying to fix!

I can't seem to replicate it :(

**Comment by MythricHD** [comment]
If you are using my config the spawner I tested with was blaze. I'll do more testing on a fresh server in a few hours

**Comment by OmerBenGera** [comment]
> 
> 
> If you are using my config the spawner I tested with was blaze. I'll do more testing on a fresh server in a few hours

I used your config with a blaze spawner

**Comment by MythricHD** [comment]
Ok after testing more its not actually due to restart. It looks like if there is a single upgraded spawner if you log out and log back in after a delay it wipes its upgrade

**Comment by OmerBenGera** [comment]
Fixed in build #36
