### ISSUE TITLE
 Item stack error

### ISSUE THREAD

**Issue by LeRoiDamien** [OmerBenGera/WildStacker#23]
Version : b37 

this error often happens with wildtools tools

http://pastebin.fr/81450

**Comment by OmerBenGera** [comment]
For no reason, there seems to be items in your world with 0 amount

**Comment by OmerBenGera** [comment]
Check out build #39

**Comment by LeRoiDamien** [comment]
Thanks i will try this

**Comment by OmerBenGera** [comment]
I pushed another update, so you should check it instead (#40)

**Comment by LeRoiDamien** [comment]
At the moment all my looks good

**Comment by LeRoiDamien** [comment]
http://pastebin.fr/82323


Hey it just started again

**Comment by OmerBenGera** [comment]
It seems like a really weird bug, as something is causing the stacked item to have a stack amount of 0

**Comment by OmerBenGera** [comment]
Has it occurred since then?

**Comment by LeRoiDamien** [comment]
Hello, not since the last time.

**Comment by OmerBenGera** [comment]
I am closing this for now.
If it happens again, lmk
