### ISSUE TITLE
WildStacker causing insane spawner lag

### ISSUE THREAD

**Issue by levtey** [OmerBenGera/WildStacker#24]
WildStacker is lagging the server immensely ticking spawners.
As seen in [this](https://spark.lucko.me/#k3f7LbZiOn) spark profiler, WildStacker spawners are taking 48% of the server tick, with slimes/magma cubes taking up most of that.
![image](https://user-images.githubusercontent.com/60494179/105654854-bd976e00-5e73-11eb-9dad-614a8aec74c8.png)

**Comment by OmerBenGera** [comment]
This is the NMS causing it... You can see that out of the 48% lag of spawners, 47.60% out of it is due to EntityTypes#a.
This cannot really be fixed on my end. Try optimizing the server in other areas, and it will probably help with this lag as well

**Comment by OmerBenGera** [comment]
I checked it again, and it looks like creation of slimes is killing your server.
What spigot jar are you using, as it doesn't seem like it's Paper

**Comment by levtey** [comment]
I am using Purpur, build 954

**Comment by levtey** [comment]
Switching back to Tuinity fixed it, thank you.

**Comment by OmerBenGera** [comment]
Perfect :)
Just a quick tip - even if you see WildStacker at the top, check it's children. If the percentage of the parent tab is the same as the children, it means the parent tab is not causing a real lag. Only when there are differences, then it causes lag (and again, having a 0.03% of a thread is not a real lag, so this needs to be considered as well)
