### ISSUE TITLE
Issue with mcmmo xp

### ISSUE THREAD

**Issue by Benntehboss** [OmerBenGera/WildStacker#26]
When stacked entities is turned on in /stacker settings my players wont get xp.. but as soon as i turn if off so mobs dont stack they start getting xp again

**Comment by OmerBenGera** [comment]
Where are you able to toggle to get XP from entities that spawned by spawners? I can't find a feature like that in mcmmo.
Also, what version of mcmmo are you using?

**Comment by Benntehboss** [comment]
Im using the lastest version of mcmmo for 1.8.9 
1.5.04-snapshot

and in mcmmo experience.yml you can find
    # Experience gained from mobs not naturally spawned will get multiplied by this value. 0 by default.
    Mobspawners:
        Multiplier: 1.0
    Breeding:
        Multiplier: 1.0

**Comment by OmerBenGera** [comment]
Check out build 49, should be fixed - update me after you've tested it

**Comment by OmerBenGera** [comment]
Hey, have you checked it?

**Comment by Benntehboss** [comment]
Works great, sry for the late answere
