### ISSUE TITLE
Space in mob title

### ISSUE THREAD

**Issue by nivcoo** [OmerBenGera/WildStacker#28]
Hello can you look this picture https://pics.edensky.fr/2021-01/30/12-16_muxl.png and this picture : https://pics.edensky.fr/2021-01/30/12-17_54Ug.png i don't know why i've space between number and "x" can you check that ?

**Comment by nivcoo** [comment]
i use WildStacker-b51 in 1.8

**Comment by nivcoo** [comment]
Same issue with spawner https://pics.edensky.fr/2021-01/30/12-41_CPWd.png

**Comment by OmerBenGera** [comment]
Hey, show me your config please, so I can understand what causes it

**Comment by nivcoo** [comment]
Yes but i have sent picture of my config before so : https://pics.edensky.fr/2021-01/30/13-13_Redr.yml

**Comment by OmerBenGera** [comment]
Fixed in build 52 :)
