### ISSUE TITLE
Picking up items causes x0 Air to appear

### ISSUE THREAD

**Issue by Gitberham** [OmerBenGera/WildStacker#3]
[https://www.youtube.com/watch?v=admDmWw4Cl0](url)

Every time I pick up an item while this plugin is enabled, it clearly displays the name of the item along with the amount of the item inside it. However, when I proceed to pick up the item it displays x0 Air for a split second before it lands into my inventory.

**Comment by OmerBenGera** [comment]
Hey, couldnt seem to replicate the issue when I tried. I will try replicating it again tomorrow and report back.

**Comment by Gitberham** [comment]
Here's my config.yml to help you with testing:
https://pastebin.com/PkZDMZ3v

**Comment by OmerBenGera** [comment]
@Gitberham Hey, please check [build #12](https://hub.bg-software.com/job/WildStacker/12/) - let me know if it works

**Comment by Gitberham** [comment]
This sadly introduced more issues.

No "pop" sound when picking up the items.
The item instantly disappears and lands in your inventory, there's no animation of it moving towards you.

[https://www.youtube.com/watch?v=tnbNsS_QNFA](url)

**Comment by OmerBenGera** [comment]
> This sadly introduced more issues.
> 
> No "pop" sound when picking up the items.
> The item instantly disappears and lands in your inventory, there's no animation of it moving towards you.
> 
> [https://www.youtube.com/watch?v=tnbNsS_QNFA](url)

What about the name... Does it still occur?

**Comment by Gitberham** [comment]
If you had watched the video I included, you would have seen that "Air" no longer appears.

**Comment by OmerBenGera** [comment]
> 
> 
> If you had watched the video I included, you would have seen that "Air" no longer appears.

I wasn't at home and couldn't watch the video. Be respectful.
I am gonna check the other issues right now

**Comment by OmerBenGera** [comment]
Check out [build #13](https://hub.bg-software.com/job/WildStacker/13/)

**Comment by Gitberham** [comment]
Perfect! This build fixed all the issues! Thank you!

**Comment by OmerBenGera** [comment]
Great :)
I am closing this!
