### ISSUE TITLE
Itemdrops from entities clip out from spawn grinders

### ISSUE THREAD

**Issue by TheAnimeGuru** [OmerBenGera/WildStacker#30]
Cheers,
Wildstacker causes a weird issue in Spawnergrinders. A vanilla grinder setup with hoppers underneath, would usually catch all the items, however with Wildstacker enabled, they tend to glitch out of the mob area, away from the monsters or even "shoot" across the screen. This does not seem to be an issue with the itemdrop stacking mechanic but more of the entity stacking mechanic(?) (as I have disabled stacking items on the floor and the issue persisted).
I use Paper-MC 1.16.5 (git-Paper-418) and the latest version of Wildstacker.

**Comment by OmerBenGera** [comment]
Hey, check out build 55
Hopefully it will fix the issue

**Comment by OmerBenGera** [comment]
Have you tried it?

**Comment by TheAnimeGuru** [comment]
Hey I am new to github, can you tell me where I can download build 55 as it says on the spigot page that its still the previous version?

**Comment by TheAnimeGuru** [comment]
I can confirm the issue has largely improved. Items do not seem shooting across the screen anymore. Thanks for looking into this.

**Comment by TheAnimeGuru** [comment]
The issue seems to have improved. However in my cavespider grinder (as an example) the items seem to like spawning in front of the entity killed, sometimes still glitching through. However in a classic grinder (e.g. Blaze) I couldnt observe the same glitch anymore.

**Comment by TheAnimeGuru** [comment]
I actually had instances of killing monsters and the items clipped through walls, not just grinders o.o
Also I am not sure, but the nametag of dropped items seems to have glitched out?

**Comment by OmerBenGera** [comment]
If you believe names of items are glitched, then open an issue with more information.
I'll see what else can be improved with the items thingy, however not sure if there's anything that is wrong on my end

**Comment by OmerBenGera** [comment]
Hey, check latest dev build 57

**Comment by TheAnimeGuru** [comment]
I checked the latest build and I have to admit it looked better in build 55.

**Comment by OmerBenGera** [comment]
Gotcha. well, I'll revert the changes and I guess we'll stick with that solution

**Comment by OmerBenGera** [comment]
Check out latest dev build, I made it so the items are dropped one block above the original location, so they shouldn't clip through slabs anymore (hopefully)
let me know if it works

**Comment by TheAnimeGuru** [comment]
They now clip through ceilings o.o
What happens if the item gets dropped at the original location? I am not sure how vanilla behaves.
If it helps if I record short clips of what is happening, let me know.

**Comment by OmerBenGera** [comment]
> 
> 
> They now clip through ceilings o.o
> What happens if the item gets dropped at the original location? I am not sure how vanilla behaves.
> If it helps if I record short clips of what is happening, let me know.

I made it so they drop at the original location, however you said they clip through slabs :(
I'll try to make them drop half a block above the original location

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by YouSeeMeRunning2** [comment]
I'm using build 80 and my items glitch out of my blaze grinder

**Comment by YouSeeMeRunning2** [comment]
![image](https://user-images.githubusercontent.com/61563491/110847673-1cd70380-82a5-11eb-8ab4-046f930b777f.png)

**Comment by OmerBenGera** [comment]
@YouSeeMeRunning2 Take a video of the issue please. I dont know what causes it tbh, but something is weird with how the items are dropped...

**Comment by OmerBenGera** [comment]
Hmm I might have found the issue, will try to fix it tomorrow

**Comment by YouSeeMeRunning2** [comment]
Still need the video?

**Comment by OmerBenGera** [comment]
@YouSeeMeRunning2 for now, no

**Comment by OmerBenGera** [comment]
@YouSeeMeRunning2 Check out latest dev build, let me know if it fixes the issue

**Comment by OmerBenGera** [comment]
@YouSeeMeRunning2 Any news regarding this?
