### ISSUE TITLE
Issue with Citizens [NPC] (Error on stopping server)

### ISSUE THREAD

**Issue by BroGoDx** [OmerBenGera/WildStacker#31]
The error pops out when i stop/restart my server. Error started to occur when i created an npc type Skeleton.

CITIZENS VERSION: https://prnt.sc/xwox24
ERROR LOG: https://pastebin.com/Q4nuqSUT

**Comment by BroGoDx** [comment]
**Full log: https://pastebin.com/b05PKcEj**

**Comment by OmerBenGera** [comment]
Should be fixed in latest build.
If it isn't, then contact Citizens regarding this
