### ISSUE TITLE
Wildstacker took a small spike tick

### ISSUE THREAD

**Issue by iSilviu-debug** [OmerBenGera/WildStacker#33]
I noticed that wildstacker threw a slight tick (42) on the server.
**Timings**: https://timings.aikar.co/?id=0a51451f79a74d189da9b67fe5c48b65#plugins

**Comment by OmerBenGera** [comment]
Take a spark profiler, timings means nothing and it's not a good tool to detect lag sources.
Closing this for now

**Comment by OmerBenGera** [comment]
Also, the timings shows that WildStacker is totally fine, so I don't know what you're even reporting

**Comment by iSilviu-debug** [comment]
> Inoltre, i tempi mostrano che WildStacker va benissimo, quindi non so nemmeno cosa stai segnalando

ah ok, so sorry for the inconvenience I had only seen a high tick with so few players
