### ISSUE TITLE
Piglin bartering has been disabled even though mob isn't nerfed

### ISSUE THREAD

**Issue by NotToBlame** [OmerBenGera/WildStacker#34]
Piglins wont barter on the latest version even though they are not set to be nerfed even when adding them to the blacklist of nerfed-entities

`  nerfed-entities:
    # A list of entities that will be nerfed.
    # If you want all entities to be nerfed, set this to [].
    whitelist:
    - EXAMPLE_MOB
    - IRON_GOLEM:SPAWNER
    - SQUID:SPAWNER
    - ZOMBIFIED_PIGLIN:SPAWNER
    - BLAZE:SPAWNER
    - ENDERMAN:SPAWNER
    - GUARDIAN:SPAWNER
    - CREEPER:SPAWNER
    - SLIME:SPAWNER
    # A list of entities that won't be nerfed.
    blacklist:
    - PIGLIN
    # A list of worlds that entities can be nerfed in.
    # If you want entities to be nerfed inside all worlds, set this to [].
    worlds: []
    # Should nerfed entities be able to teleport?
    teleport: false`

**Comment by OmerBenGera** [comment]
You can't have both whitelist and blacklist enabled for nerfed entities.
Delete the piglins from the blacklist section

**Comment by NotToBlame** [comment]
Was still having this issue before adding PIGLIN to the blacklist. Was suggested to add it in the support Discord

**Comment by OmerBenGera** [comment]
Are you sure able to replicate the issue with only WildStacker installed on your server?

**Comment by OmerBenGera** [comment]
I could replicate the issue - seems like piglins pick up items but don't bartering.
Gonna check that out

**Comment by OmerBenGera** [comment]
Hey, it's fixed in build 56 :)
