### ISSUE TITLE
WildStacker Entity Lag

### ISSUE THREAD

**Issue by Callum0508** [OmerBenGera/WildStacker#347]
### Minecraft's Version

1.12.2
Paper

### Plugin's Version

3.6.0-DEVb217

### Describe the bug

Gradually the server will lag overtime from entity lag from stacked mobs, WildStacker entity clear will clear the mobs just fine but /stacker stats will still show a high amount of entities - the entities seem to still be there after clearing entities which overtime adds up and causes massive lag to the server and crashes.

### To Reproduce

Download latest WildStacker version
Download WildStacker config (below)
Leave server running 24/7
Keep a bunch of stacked spawners loaded 
Issue usually starts happening within 12-24hours

### Additional Information

https://pastebin.com/d1JxaJMe - WildStacker Config
https://pastebin.com/dvfkvUTp - WildStacker Error in Console
https://spark.lucko.me/RDFz42uyma - Spark report showing entity lag

**Comment by OmerBenGera** [comment]
There is no need to bump issues, I will look into that once I have time.

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it's better.
I found one issue from WildStacker and hopefully it's better in latest update.

**Comment by Callum0508** [comment]
Thanks, just put the new version on will keep you updated

**Comment by Callum0508** [comment]
error in console when server lags alot: https://i.imgur.com/Ort3VGg.png 

I also see this alot in the console: https://i.imgur.com/Ekg8OIr.png
