### ISSUE TITLE
Mobs spawn on top of Spawners

### ISSUE THREAD

**Issue by TheAnimeGuru** [OmerBenGera/WildStacker#35]
Cheers, there is a little issue that is not fixable with stacked spawners by any vanilla means. If a mob spawns on top of a spawner. The armor stand prevents from build blocks or place water to push spawned mobs down.
If there would be a setting, that prevents mobs from spawning on top of a spawner that would be great, so they dont get stuck and keep building up.

**Comment by OmerBenGera** [comment]
so just to be corrected: the issue is with the hologram blocking the ability to place blocks ontop of spawners, and not them spawning on top of spawners (as that's possible in vanilla as well)
What version of minecraft are you using?

**Comment by OmerBenGera** [comment]
I just tested it on my localhost and I can place blocks on top of spawners without any issues

**Comment by TheAnimeGuru** [comment]
I tested it again with build 57, and it didnt work because I pressed shift. So false alarm! Apologies
