### ISSUE TITLE
Health on husk

### ISSUE THREAD

**Issue by WarnDa** [OmerBenGera/WildStacker#359]
### Minecraft's Version

1.16.5 airplane

### Plugin's Version

b222

### Describe the bug

Sometimes stacked husk get 85 health, it's the only mob which get this bug, and I don't know why.
I don't get other plugin related to mobs.
Mobs are spawned by a spawner, and the bug is random, it doesn't happen always.

### To Reproduce

Spawn husk, and sometimes they will get more health, it's rare, but it happens

### Additional Information

Doesn't happen on all mobs (or player didn't report it)

<img width="573" alt="Screenshot_6713" src="https://user-images.githubusercontent.com/31826333/138272264-1afa8a09-6f1c-4a00-8b51-8d4fb41eeaa6.png">

**Comment by JasonHorkles** [comment]
I've also encountered this issue. I'm currently investigating what setting causes it, as it seems to only happen with my config and not the default one
