### ISSUE TITLE
Issues with MoreMobHeads

### ISSUE THREAD

**Issue by TheAnimeGuru** [OmerBenGera/WildStacker#36]
Cheers,
I am running MoreMobHeads on my Server, and I noticed that the stacked wither skeletons drop heads of the stackname and Wither Skeleton after (its set to only drop vanilla heads). For some reason, it registers as a player?

**Comment by OmerBenGera** [comment]
Contact the moremobheads developer regarding this, I am not familiar with the plugin and I can't help with that
