### ISSUE TITLE
natural growing chickens do not stack with others

### ISSUE THREAD

**Issue by ejdzeys** [OmerBenGera/WildStacker#360]
### Minecraft's Version

1.8.8 paper

### Plugin's Version

3.6.0

### Describe the bug

When the hatched baby chickens grow up, they are not stacked with other large chickens.

### To Reproduce

It creates a big lag problem on servers with a large chicken farm as the hatched chickens do not stack with each other when they grow up.

**Comment by YouSeeMeRunning2** [comment]
Tested with #222, used /ws simulate and it said successful but couldn't get them to stack. I've enabled stack interval and tried that way as well.
