### ISSUE TITLE
Items on the floor do not seem to show the holographic name anymore in the latest build

### ISSUE THREAD

**Issue by TheAnimeGuru** [OmerBenGera/WildStacker#37]
Hey,
I noticed that the items on the floor do not show the usual nametag above them anymore. In the settings its toggled on, thats why I am confused.

**Comment by OmerBenGera** [comment]
Upload your config to pastebin and send it here, as it works just fine for me

**Comment by TheAnimeGuru** [comment]
I have the checked what the issue is and I apologize, this was a client sided issue. Sorry!
