### ISSUE TITLE
Certain unstackable items stack in the inventory.

### ISSUE THREAD

**Issue by Gitberham** [OmerBenGera/WildStacker#4]
Certain items such as beds and buckets including contents will stack in the inventory after throwing them on the ground.

**Expected behaviour**: 
![afbeelding](https://user-images.githubusercontent.com/76908688/103489729-ba7e0480-4e16-11eb-8694-b4ca4476d17d.png)

**Items stacked on the floor**:
![afbeelding](https://user-images.githubusercontent.com/76908688/103489749-d08bc500-4e16-11eb-879c-bced35537851.png)

**Items after picking it back up**:
![afbeelding](https://user-images.githubusercontent.com/76908688/103489753-dc778700-4e16-11eb-8d3d-413675cb7e69.png)

**Comment by OmerBenGera** [comment]
Look for "fix-stack" and set it to true in the config file of WildStacker.
