### ISSUE TITLE
MobMetaFlagType java error in wildstacker

### ISSUE THREAD

**Issue by Yamamot00** [OmerBenGera/WildStacker#40]
I'm having this issue on my server when I enable the entities to stack and I don't know the problem.
There isn't any other plugin that I use that changes the mob beravior other than MobFarmManager(this only limits the spawn rate)
but it doesn't do anything to the stacks I think.
Here is the error: https://pastebin.com/8ShRzDK4

edit: This edit is not related to the issue itself. is there any planned update to support "LevelledMobs" plugin? when i enable this plugin my levelledmobs don't spawn.(I disabled the plugin before creating this issue)

**Comment by OmerBenGera** [comment]
Update mcmmo
About levelledmobs - open an issue regarding this, explain how levelledmobs work, what it does, etc

**Comment by Yamamot00** [comment]
wow that was fast, thank you i will try that and make another issue. will update here if the mobmetatype still persist

**Comment by Yamamot00** [comment]
sorry to be late. i installed the newer version of mcmmo and the problem is fixed, Thank you very much.
