### ISSUE TITLE
LevelledMobs support on WildStackers

### ISSUE THREAD

**Issue by Yamamot00** [OmerBenGera/WildStacker#41]
LevelledMobs simply increase the difficulty on their server, its considered a Mechanic/fun plugin. the plugin simply give mobs a Level to then starting from 1 to 10(configurable) and their strenght and hearts increase by level.

What i want is so that we could put in the Wildstacker config the name of the mob entity and the levelledmobs would take place on the spawning of the mob. 
I tried putting the names of the mob to not stack in config.yml/Entities/Blacklist but even so my mobs dont get replaced to the levelledmobs.

it would be great to have support from both plugins.

**Comment by OmerBenGera** [comment]
The issue might be because that plugin checks for mobs based on their names instead of caching their UUID or something.
Are you able to send me a link to the spigot page of the plugin?

**Comment by Yamamot00** [comment]
https://www.spigotmc.org/resources/levelledmobs-for-1-14-x-1-16-x.74304/

**Comment by OmerBenGera** [comment]
Hey, check out build 62, it should have support for levelled mobs.

**Comment by Yamamot00** [comment]
Where this build is located? I just simply downloaded the latest version

**Comment by OmerBenGera** [comment]
https://bg-software.com/wildstacker/
You can find all links to all dev builds of the plugin on this page. Locate build 63 (not 62, my bad) and download it from here :)

**Comment by Yamamot00** [comment]
I tried with the build 63 and it did not worked out, i also blacklisted the mobs that i want to be levelled and searched around the world for then but they not get the levels, also tried to spawn manually by the commands from levelledMobs but it only spawned the normal one to without levels

Did wildstackers got free? i was using the paid version before installing the 63 build. It should have staid for premiun your plugin =/ such a good one

**Comment by OmerBenGera** [comment]
It worked fine for me, so you probably do something wrong.
Use default config files and try it again I guess

**Comment by OmerBenGera** [comment]
Also, show me your LevelledMobs config file

**Comment by Yamamot00** [comment]
[configtest.zip](https://github.com/OmerBenGera/WildStacker/files/5934521/configtest.zip)

here is it

**Comment by OmerBenGera** [comment]
Upload it to pastebin, I am not downloading it.

**Comment by Yamamot00** [comment]
i dont think uploading the settings only to the pastebin will get you more information but here is it:

LeveledMobs: https://pastebin.com/Ljr5d1cQ
Wildstacker: https://pastebin.com/xFJFzygQ

**Comment by OmerBenGera** [comment]
`# In what worlds can levelled mobs spawn?
# By default, levelled mobs are spawned in all worlds.
allowed-worlds-list:
 
  # What mode should the world list use?
  # 'BLACKLIST' = The worlds in the list are blocked, but all the other ones are allowed
  # 'WHITELIST' = The worlds in the list are allowed, but all the other ones are blocked
  # 'ALL' = This list is skipped, and all worlds are allowed.
  mode: 'WHITELIST'
 
  # The list of worlds to apply the blacklist or whitelist to.
  # Simply enter the name of the world here. Case-sensitive!
  list:
    - 'example_world'`
First of all, you only allow levelled mobs in a world called "example_world".
Secondly, you have both "spawn-distance-levelling" and "y-distance-levelling" disabled, then how would it even work?

You should fix your levelled mobs config so it first works, and then it will also work with WildStacker.
