### ISSUE TITLE
Custom names not showing properly

### ISSUE THREAD

**Issue by Ibesh** [OmerBenGera/WildStacker#42]
Hi,
With the latest version (3.5.1) there seems to be an issue where anything behind the {0} does not get shown in-game. 
Currently I the item stack has as custom-name: `'&f{1} &e(&bx{0}&e)'`.
This is displayed as shown below:
![image](https://user-images.githubusercontent.com/43782718/106931946-6cab3380-6717-11eb-8142-3bbf4bf8cc80.png)

As far as I have noticed, this issue also applies to mobs and spawners.

Server version: Paper 1.16.5
Plugin version: 3.5.1

I hope I have provided enough information, if not then let me know :)

**Comment by OmerBenGera** [comment]
Use latest dev build, let me know if it still happens

**Comment by Ibesh** [comment]
Still happens with the latest dev-build.

**Comment by OmerBenGera** [comment]
As a temp fix, it might work if you add a color to the end of the name. I will check it out once I can

**Comment by Ibesh** [comment]
Already tried that, but didn't work unfortunatly.
And take your time, really no hurry behind this tbh.

**Comment by OmerBenGera** [comment]
Fixed in build 60 :)
