### ISSUE TITLE
Mobs From Skeleton Spawner Ignoring Minimum Stack Requirement

### ISSUE THREAD

**Issue by anselhelm** [OmerBenGera/WildStacker#43]
Good day,

I'm using WildStackers 3.5.1, which is the latest version showing on SpigotMC. It appears that at least skeletons (possibly other mobs) from spawners (possibly otherwise) are ignoring the minimum stacking figure set in config.yml. My current setting is:

minimum-required:
all: 25

I've also tried it with
SKELETON: 25

In both cases, skeletons from the spawner merge before hitting the 25 minimum threshold to merge. This means that I've had to set a maximum stack limit ("limits:") so that a skeleton spawner farm still functions, as it requires the skeletons to push each other into the water elevator. The basic layout of the farm mirrors this design: https://www.youtube.com/watch?v=WlvZjZIvMds

I am fully open to the possibility that it's user error by me. However, I've experienced no other issues and have found the configuration to be quite straight-forward.

Please let me know what information would be useful to investigate this and I'll happily provide further details.

**Comment by OmerBenGera** [comment]
Please use latest dev build - you can find it on https://bg-software.com/wildstacker/
Let me know if it still occurs when using this version.

**Comment by anselhelm** [comment]
Sorry for my slow reply. I am not experiencing the issue with the latest development version (b63), so I consider this resolved :)
