### ISSUE TITLE
Spawner Upgrades 

### ISSUE THREAD

**Issue by FadedLake64040** [OmerBenGera/WildStacker#45]
When placing down an upgraded spawner it always reverts to the default upgrade.
tried it on a server without any other plugins and it still wont work

plugin version - Dev Build 63
minecraft version - spigot 1.12.2
config.yml - https://pastebin.com/GGBBNS5W
server log - https://pastebin.com/wA4b2tQD

**Comment by OmerBenGera** [comment]
You placed a cow spawner and it just reverted to normal?

**Comment by FadedLake64040** [comment]
yes

**Comment by OmerBenGera** [comment]
Take a clip of the issue and upload it to youtube or another streaming service

**Comment by FadedLake64040** [comment]
idk if i can it takes like 5 mins to upload a simple picture

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
