### ISSUE TITLE
Mobs drops spawning to high

### ISSUE THREAD

**Issue by Benntehboss** [OmerBenGera/WildStacker#47]
Hello, im using the plugin for my skyblock server, and when people are making IG farms, the iron spawns in head high = it burns instant in lava, im using build 63 and i tryed version 3.5.1 and it works fine there, however i needed the newer build for mcmmo to work, it this something u can look into?

- Bennetheboss

**Comment by Benntehboss** [comment]
I done some research if they have 2½ block of air they stand in, 95% of the time, the drop survives, i dont know if that helps anything tho

**Comment by Benntehboss** [comment]
https://gyazo.com/6199b1b244869cadb263a2b4f9255bec
https://gyazo.com/49230d9f06ecea39fe9e7ebf88fd9c07

**Comment by Benntehboss** [comment]
like that it works fine in the build 63

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it fixes the issue

**Comment by OmerBenGera** [comment]
Any news?

**Comment by Benntehboss** [comment]
sry i havent had the time to try it out, i will look into it later today

**Comment by Benntehboss** [comment]
it seems to work fine for me now,

**Comment by OmerBenGera** [comment]
Great, I am closing this for now
