### ISSUE TITLE
Mob Agro/Fuse not resetting on death

### ISSUE THREAD

**Issue by Paul19988** [OmerBenGera/WildStacker#48]
# What happens?

Mobs do not reset their current agro/fuse when dying and spawning another mob after them,
This can cause Creepers to explode rapidly as they can have a 90% fuse and instantly explode.

# Possible solution

Add list for ability to have mobs reset agro/fuse upon death to avoid this issue

**Comment by OmerBenGera** [comment]
I couldn't really get this to work, and it doesn't seem to be possible (I might be wrong).
The only thing I managed is to cause creepers to have their fuse reset, however it causes the creeper to stay in the "almost blown" stage until the creeper has its target reset.
I'll try to keep playing with it, however from my testings it doesn't seem an easy task as I thought it would be. Do you know about plugins that have a similar feature, so I can ask the developers how they achieved it?

**Comment by OmerBenGera** [comment]
Hey, please upload this feature request to the discussions area.
I am moving all the feature requests from the issues tracker :)

**Comment by OmerBenGera** [comment]
I moved your feature request to the discussions section.
