### ISSUE TITLE
EntityDamageByEntityEvent

### ISSUE THREAD

**Issue by klaidoshka** [OmerBenGera/WildStacker#49]
**Yatopia** 1.16.5
**WildStacker** 3.5.1

[This](https://pastebin.com/5LxprrBs) (https://pastebin.com/5LxprrBs) error happens when trying to kill entities... something with enchants... but why? Item isn't enchanted, just simple sword or axe... or anything, it still happens.
Is it plugin's fault or Yatopia's? 😌

**Comment by OmerBenGera** [comment]
Your spigot jar can't find the sweeping edge enchantment for no reason.

**Comment by klaidoshka** [comment]
Oh, okay. Then it's the issue with **CMI** (by Zrips) and... **WildStacker** ? I guess?

Sorry for the late answer, was night-time, but anyways...
The situation is that we're going to have **1.16.5** with **1.8** PvP and had to disable **Sweeping Edge** enchant by **CMI**'s _/disableenchant_ feature, which removes all the disabled enchants from anywhere.

I don't know if Mending enchant could be a problem too, but we also have it disabled in our server, because we have a custom plugin like "Blacksmith", where people fix other people's items by certain prices, the system wouldn't work if Mending existed. 😫

**Comment by OmerBenGera** [comment]
I'll see what can be done regarding this.
This is a weird system of CMI not gonna lie, not sure why they even added such thing, as it can break other plugins that interact with sweeping edge...

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it works

**Comment by klaidoshka** [comment]
`This is a weird system of CMI not gonna lie, not sure why they even added such thing, as it can break other plugins that interact with sweeping edge...`
I think they mention something like this in their wiki or command itself, don't really remember right now... So I guess it's my fault in the end, just didn't think that this could be a problem 😌

Anyways, I downloaded the latest build, shot the server up, killed quite a few dozens of mobs and nothing 'wrong' happened in-game nor in the console, I think it's fixed!!! ♥ Thank you very much, haha.

If it happens again, I will make sure to reopen the issue or write a new one 🙌
Thank you, again! =]
