### ISSUE TITLE
PlayerPickupItemEvent is always cancelled

### ISSUE THREAD

**Issue by ezzerland** [OmerBenGera/WildStacker#5]
I had thought I previously reported this but it's an issue in the latest build.

Even with item stacking disabled, all item pick up events are still cancelled and handled by wildstacker. I recall being told this was to deal with improper stacked items and that it would be addressed by checking max stack count and only cancelling when necessary, but this is currently causing an issue for 2 other plugins that use the event.

Thanks

**Comment by OmerBenGera** [comment]
The pickup event is cancelled only if one of the followings are true:
- Item stacking is enabled
- The amount of the item is above the max stack size
- Buckets stacking is enabled and you pickup buckets

Is any of these conditions true?

**Comment by ezzerland** [comment]
No. It functions for all items, item stacking is not enabled and the items they are picking up are just normal stacks. If they pick up a stack that is just 1 single item that is not stacked, the event fires correctly. But every stack is processed and event is cancelled.

**Comment by OmerBenGera** [comment]
I added a listener in MONITOR for PlayerPickupItemEvent, I cancelled

> 
> 
> No. It functions for all items, item stacking is not enabled and the items they are picking up are just normal stacks. If they pick up a stack that is just 1 single item that is not stacked, the event fires correctly. But every stack is processed and event is cancelled.

I added a listener in MONITOR for PlayerPickupItemEvent and printed if the event is cancelled. I disabled stacking of items and it printed "false". Please try replicating the issue on a server with only WildStacker installed and the plugin that it conflicts with

**Comment by ezzerland** [comment]
Tried to replicate on localhost and couldn't. Went back on to live server and suddenly everything there is working as intended. If I run into any further issue with it I'll make a new report if I can identify what's causing it.

Thanks :)
