### ISSUE TITLE
multiplication problem

### ISSUE THREAD

**Issue by TheMartyCZ** [OmerBenGera/WildStacker#51]
Hello, I discovered a problem with reproduction. I can reproduce them over and over again.

https://user-images.githubusercontent.com/45405349/108199332-22658180-711d-11eb-9e3c-91ba7f6a33eb.mp4

SSSPigot 1.16.3
WildStacker #69

**Comment by OmerBenGera** [comment]
Enable smart breeding

**Comment by TheMartyCZ** [comment]
The problem still persists.

**Comment by OmerBenGera** [comment]
Try it with regular Paper and check if it still occurs

**Comment by TheMartyCZ** [comment]
On spigot 1.16.3 its working. 
Please reply to me about closed issues on ssb2. (ore generator)

Thank you.

**Comment by OmerBenGera** [comment]
Wait, you don't want me to fix it with SSSpigot?

**Comment by TheMartyCZ** [comment]
No, I wrote in support of SSpigot and I solved it with them and it already works as it should.
