### ISSUE TITLE
Breeding not working?

### ISSUE THREAD

**Issue by Gitberham** [OmerBenGera/WildStacker#52]
Players started reporting breeding not working coincidentally after I changed my config.yml to blacklist donkeys, bats, cods, salmon, pufferfish and tropical fish (to prevent them from being stacked)

After doing some testing in both a test world and the default world, I can indeed confirm that breeding is broken. I've included my config.yml, but I am also not sure if it is WildStacker that's causing this.

Players have also mentioned that breeding works sometimes (Stack of 100 resulting in only 10 baby animals). I have not been able to reproduce this.

Video: https://www.youtube.com/watch?v=JWTF6h7kZwM
Config: https://pastebin.com/qupczB2c

**Comment by OmerBenGera** [comment]
Version of WildStacker? Version of Spigot?

**Comment by Gitberham** [comment]
WildStacker 3.5.1
yatopia-1.16.5-yatoclip-b30

**Comment by Gitberham** [comment]
I just created a test server where I've only installed WildStacker. The results appear to be 50/50 here. Sometimes it'll breed succesfully and make the baby, and sometimes it'll go into breeding phase to just stack into each other before finishing the process.

Uninstalling WildStacker (server with no plugins at all) makes the breeding phase always work.

**Comment by Gitberham** [comment]
The test server was running on the latest Paper version.

**Comment by OmerBenGera** [comment]
Try enabling smart breeding for the time being

**Comment by Gitberham** [comment]
I've enabled it for now, but would like to turn it off as soon as possible. :)

**Comment by OmerBenGera** [comment]
Fixed in build #73 - it was caused because of the stack interval, as the two entities were stacked together before the breeding process was completed. I added an inlove status check (a bit different then can be bred), which will make sure entities that are in love cannot stack together.
