### ISSUE TITLE
PlayerExpChangeEvent before adding exp to player

### ISSUE THREAD

**Issue by TouchBrown** [OmerBenGera/WildStacker#53]
This should run the PlayerExpChangeEvent first then give exp based on that so that people can use exp boosters when having auto-exp enabled.  Would be a very quick fix.
https://github.com/OmerBenGera/WildStacker/blob/2198246c83533810c9b67d1ebc32c8fdf73f571d/src/main/java/com/bgsoftware/wildstacker/listeners/EntitiesListener.java#L443

**Comment by OmerBenGera** [comment]
I am pretty sure giveExp runs the event

**Comment by TouchBrown** [comment]
As dumb as it sounds it doesn't in 1.12 at least 
https://gyazo.com/0d2d05524b349835d120e0aeba9a6667

**Comment by OmerBenGera** [comment]
Fixed in latest dev build :)
