### ISSUE TITLE
Localisation

### ISSUE THREAD

**Issue by Redstylt** [OmerBenGera/WildStacker#55]
The plugin doesn't support the lang of minecraft.
I mean the entities, spawner, etc are renamed in english. They don't stay in the local langage.
We should be able to set a localisation in config file or it should detect the client langage (like luckperms)

MC version : 1.16.5
WS version : 69
SS2 version : 68

**Comment by OmerBenGera** [comment]
I don't know if that's possible, as the server doesn't have versions of all entity names for every language.
You should use custom-names instead.

**Comment by Redstylt** [comment]
you may should add a file that contain the list of entities (like the plugin Divinedrop https://www.spigotmc.org/resources/%E2%98%AF-divinedrop-%E2%98%AF-awesome-drop-management-1-8.51715/ )
And let the Custom-names file override this file.

**Comment by OmerBenGera** [comment]
> 
> 
> you may should add a file that contain the list of entities (like the plugin Divinedrop https://www.spigotmc.org/resources/%E2%98%AF-divinedrop-%E2%98%AF-awesome-drop-management-1-8.51715/ )
> And let the Custom-names file override this file.

This is not an issue tho, you request here a totally new feature.
Features are not added by me to the plugin anymore
