### ISSUE TITLE
Nearby entites limit doesnt work

### ISSUE THREAD

**Issue by Redstylt** [OmerBenGera/WildStacker#56]
In my island as an admin in my superiorworld the "max nearby entites" look like doesn't affect the spawn.
As I have a stack of 100 pandas just next to my lvl one panda's spawner.

Also would be great to be able to change this settings for each spawner.

MC version : 1.16.5
WS version : 69
SS2 version : 68

**Comment by OmerBenGera** [comment]
A stack of 100 pandas is considered as one entity. That's an intended behavior, and changing it makes no sense, as spawners will act as vanilla otherwise.

**Comment by Redstylt** [comment]
Sorry but it should be possible to find a middle way. Because if I want to limit the animal spawn to prevent players from stacking too much while keeping ideal performances for the server, it should be possible to tell the plugin to take into account the number of animals in the stack(s) and not the number of entities.

**Comment by OmerBenGera** [comment]
> 
> 
> Sorry but it should be possible to find a middle way. Because if I want to limit the animal spawn to prevent players from stacking too much while keeping ideal performances for the server, it should be possible to tell the plugin to take into account the number of animals in the stack(s) and not the number of entities.

It was already suggested, now waiting for someone to add support for it :)
I am not adding new features to the plugin anymore.

**Comment by Redstylt** [comment]
Alright so could you let this opened and class it like "request feature" .
Maybe a nice dev will see that and take a look at it :D

**Comment by OmerBenGera** [comment]
I prefer feature requests to stay on the discord
