### ISSUE TITLE
Wild. stacker..

### ISSUE THREAD

**Issue by iSilviu-debug** [OmerBenGera/WildStacker#57]
Wildstacker seems to give me memory leaks and a lowering of the absurd tps. I don't understand why but wildstacker is unusable for me. Each time it goes to 14-17-18-20-17 tps.

**Spark**: https://spark.lucko.me/#cMgotqTAEr
spark

**Comment by OmerBenGera** [comment]
WildStacker has no memory leaks. If you believe it causes lag, take a spark profiler - the one you provided is not helpful.
Use /spark sampler and /spark sampler --stop when the lag occurs so I know what causes it.

**Comment by OmerBenGera** [comment]
Also, make sure you use latest dev build of WildStacker

**Comment by iSilviu-debug** [comment]
**Spark sampler**: https://spark.lucko.me/#qQHc1dE8tB

**Comment by iSilviu-debug** [comment]
Maybe I'm wrong but I have serious memory leak problems

**Comment by OmerBenGera** [comment]
> 
> 
> Maybe I'm wrong but I have serious memory leak problems
> and many connect wildstacker

Any prove for that?

**Comment by OmerBenGera** [comment]
> 
> 
> **Spark sampler**: https://spark.lucko.me/#qQHc1dE8tB

All the lag you have has nothing to do with WildStacker...
Maybe I missed something, but I don't see anything there

**Comment by iSilviu-debug** [comment]
> > **Spark sampler**: https://spark.lucko.me/#qQHc1dE8tB
> 
> All the lag you have has nothing to do with WildStacker...
> Maybe I missed something, but I don't see anything there

then can you explain this to me?
**Timings**: https://timings.aikar.co/?id=fe8212cf43b3427bb54eb6b901b216fc

**Comment by OmerBenGera** [comment]
> 
> 
> > > **Spark sampler**: https://spark.lucko.me/#qQHc1dE8tB
> > 
> > 
> > All the lag you have has nothing to do with WildStacker...
> > Maybe I missed something, but I don't see anything there
> 
> then can you explain this to me?
> **Timings**: https://timings.aikar.co/?id=fe8212cf43b3427bb54eb6b901b216fc

According to this timings, the lag comes from mainly 3 sources:
1) Tile entity ticking in the world mono something
2) Entity ticking in that same world
3) Entity ticking in the default_nether world

I am closing this as everything looks fine in both the timings and spark.

**Comment by iSilviu-debug** [comment]
@OmerBenGera This is one thing you have disproved about the memory leak ... 

![IMG_20210411_154751_271](https://user-images.githubusercontent.com/67197594/114306875-98fb7b80-9add-11eb-9103-f0b29086ae57.jpg)

I'm sorry you didn't listen to me some time ago where I was asking for help but it's safer to go without plugin than with wildstacker ..

**Comment by OmerBenGera** [comment]
> 
> 
> @OmerBenGera This is one thing you have disproved about the memory leak ...
> 
> ![IMG_20210411_154751_271](https://user-images.githubusercontent.com/67197594/114306875-98fb7b80-9add-11eb-9103-f0b29086ae57.jpg)
> 
> I'm sorry you didn't listen to me some time ago where I was asking for help but it's safer to go without plugin than with wildstacker ..

All cached entities in EntitiesGetter are removed from this cache after 5 seconds of writing to the list, not sure why it happens but it shouldn't occur. Might be another issue causing it to happen, it's not possible to know with only a screenshot that doesn't tell much about the issue
