### ISSUE TITLE
WorldGuard regionNames error

### ISSUE THREAD

**Issue by Chappy202** [OmerBenGera/WildStacker#6]
Wildstacker constantly spams the console with an error that seems to be related to fetching the regions from worldguard:

`03.01 12:46:46 [Server] WARN [WildStacker] Task #65054 for WildStacker v3.5.0 generated an exception
03.01 12:46:46 [Server] INFO java.lang.NoClassDefFoundError: com/sk89q/worldguard/WorldGuard
03.01 12:46:46 [Server] INFO at com.bgsoftware.wildstacker.hooks.WorldGuardHook$WorldGuardProvider.getRegionNames(WorldGuardHook.java:34) ~[?:?]
03.01 12:46:46 [Server] INFO at com.bgsoftware.wildstacker.hooks.WorldGuardHook.getRegionsName(WorldGuardHook.java:24) ~[?:?]
03.01 12:46:46 [Server] INFO at com.bgsoftware.wildstacker.objects.WStackedEntity.runStackCheck(WStackedEntity.java:283) ~[?:?]
03.01 12:46:46 [Server] INFO at com.bgsoftware.wildstacker.objects.WStackedEntity.lambda$runStackAsync$2(WStackedEntity.java:311) ~[?:?]
03.01 12:46:46 [Server] INFO at com.bgsoftware.wildstacker.nms.NMSAdapter_v1_12_R1.lambda$getNearbyEntities$0(NMSAdapter_v1_12_R1.java:266) ~[?:?]
03.01 12:46:46 [Server] INFO at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174) ~[?:1.8.0_265]
03.01 12:46:46 [Server] INFO at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[?:1.8.0_265]
03.01 12:46:46 [Server] INFO at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:1.8.0_265]
03.01 12:46:46 [Server] INFO at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_265]
03.01 12:46:46 [Server] INFO at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_265]
03.01 12:46:46 [Server] INFO at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_265]
03.01 12:46:46 [Server] INFO at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_265]
03.01 12:46:46 [Server] INFO at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566) ~[?:1.8.0_265]
03.01 12:46:46 [Server] INFO at com.bgsoftware.wildstacker.nms.NMSAdapter_v1_12_R1.getNearbyEntities(NMSAdapter_v1_12_R1.java:267) ~[?:?]
03.01 12:46:46 [Server] INFO at com.bgsoftware.wildstacker.utils.entity.EntityUtils.lambda$getNearbyEntities$5(EntityUtils.java:457) ~[?:?]
03.01 12:46:46 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[patched_1.12.2.jar:git-Paper-1618]
03.01 12:46:46 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[patched_1.12.2.jar:git-Paper-1618]
03.01 12:46:46 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:840) ~[patched_1.12.2.jar:git-Paper-1618]
03.01 12:46:46 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1618]
03.01 12:46:46 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1618]
03.01 12:46:46 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1618]
03.01 12:46:46 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]`

https://sourceb.in/HSpsh8bvDD

Edit:
The server is runnig Paper-1.12.2
WorldGuard: 6.2.2 (The latest 1.12.2 supported version)
FAWE (Worldedit): 19.11.13-5505943-1282-22.3.5 (Found to be the most stable on 1.12.2)

**Comment by OmerBenGera** [comment]
Check out [build #11](https://hub.bg-software.com/job/WildStacker/11/)
