### ISSUE TITLE
Spigot Server Crash - Possibly Due To Wildstacker

### ISSUE THREAD

**Issue by anselhelm** [OmerBenGera/WildStacker#61]
Hi,

I've added the details of a recent server crash to Pastebin:
[https://pastebin.com/ke2bS8JF](https://pastebin.com/ke2bS8JF)

It seems to suggest that Wildstacker is responsible for the crash. There is another plugin listed ([ChopChop](https://www.spigotmc.org/resources/chopchop.86728/)), so I'll make the developer aware also, just in case it's a compatibility issue between the plugins.

Thanks for looking into this.

**Comment by OmerBenGera** [comment]
What was the TPS of the server before the crash?
It seems like the server had low TPS, which caused a simple task to hang the server and it crashed eventually.
I don't see how WildStacker nor ChopChop could cause the crash.

**Comment by anselhelm** [comment]
Unknown TPS prior to the crash. Nothing of any stress was being carried out. The server itself currently exists on a Ryzen 5 1600 machine, which is no slouch, though it is being upgraded shortly to a Ryzen 5 3600. I've only just started to get my head around the crash logs, as I'm still a fair novice at Spigot servers and it's only used for a handful of friends/relations, but I've previously seen crashes like that one on a different PC with an even more powerful CPU (Ryzen 7 5800X).

If there's nothing that can be investigated from this, I will fully understand. However, if there's anything else I can run to provide more information to you, please advise.

**Comment by OmerBenGera** [comment]
> 
> 
> Unknown TPS prior to the crash. Nothing of any stress was being carried out. The server itself currently exists on a Ryzen 5 1600 machine, which is no slouch, though it is being upgraded shortly to a Ryzen 5 3600. I've only just started to get my head around the crash logs, as I'm still a fair novice at Spigot servers and it's only used for a handful of friends/relations, but I've previously seen crashes like that one on a different PC with an even more powerful CPU (Ryzen 7 5800X).
> 
> If there's nothing that can be investigated from this, I will fully understand. However, if there's anything else I can run to provide more information to you, please advise.

It doesn't really matter what the aspects of the server are, as the Minecraft's code doesn't really take advantage of all of the CPU cores etc.
Therefore, servers can lag on really decent servers as well. I really think it was due to overall lag of the server that caused it to crash. I am closing this for now
