### ISSUE TITLE
Natural Spawned Mobs Invincible

### ISSUE THREAD

**Issue by Skizzles** [OmerBenGera/WildStacker#63]
I had recently changed my wildstacker settings from stacking natural mobs to not stacking them. There was a left over stacked cow that seems to be invincible.

https://screenshots.skizzles.me/wAnA3/VosIZaxA80.mp4

When a player breeds the cow it just dupes hundreds of cows and never ends.

**Comment by OmerBenGera** [comment]
So if you have natural mobs to stack, and then you disable it once there's already a mob, it cannot be killed?
What's your spigot version & wildstacker version?

**Comment by Skizzles** [comment]
That is correct

Purpur 1.16.5
WildStacker-b69 (Realize I am a few behind)

**Comment by OmerBenGera** [comment]
Don't update, as newer dev builds will probably not fix it.
I will check it out today hopefully

**Comment by Skizzles** [comment]
Alright, thank you!

**Comment by OmerBenGera** [comment]
Hey, it seems like only the names are not updated, however the actual stack size is still decreasing.
Does it happen for you as well? (You can check that with /ws inspect)

**Comment by chipscaped** [comment]
I also have been having this issue for some time, I am using Purpur 1.16.5 but this also happens on paper
I am using the latest stable build of wildstacker, no one is able to damage them at all they do not even turn red or take knockback it is as if invincible is checked for worldguard flags.

**Comment by OmerBenGera** [comment]
> 
> 
> I also have been having this issue for some time, I am using Purpur 1.16.5 but this also happens on paper
> I am using the latest stable build of wildstacker, no one is able to damage them at all they do not even turn red or take knockback it is as if invincible is checked for worldguard flags.

Might be because of mcmmo, idk - as I can't seem to replicate the issue.
Also, it doesn't sound like the same issue, as on Skizzles's video, the red animation is shown and entities are just never die.

**Comment by Skizzles** [comment]
> Hey, it seems like only the names are not updated, however the actual stack size is still decreasing.
> Does it happen for you as well? (You can check that with /ws inspect)

Sorry for late reply, I checked stacked sizes before but I will see if I can find another in the future. But they do seem to never die tho because no death animations are played.

**Comment by thecenters** [comment]
Having the same issue. Had YouSeeMeRunning get on my server to test and it did not kill the mob. I'm using purpur but I had this issue on paper as well. I do not use mcmmo.

Steps to re-create:
- Turn mob stacking on
- Allow mobs to stack
- Turn mob stacking off
- Attack a stacked mob until you kill it and see the death animation (example 4x Chicken)
- mob will glitch and is now invincible (and it's still called 4x Chicken)


I use WildStacker for item stacking and spawner stacking. So it bugs out in this situation. Invincible mobs cannot be killed with restarting, by using /butcher, or with the /kill command

Attached is a copy of my config file

[config.txt](https://github.com/OmerBenGera/WildStacker/files/6133899/config.txt)

**Comment by OmerBenGera** [comment]
> 
> 
> Having the same issue. Had YouSeeMeRunning get on my server to test and it did not kill the mob. I'm using purpur (git-Purpur-992) but I had this issue on paper (git-Paper-457) as well. I do not use mcmmo.
> 
> Steps to re-create:
> 
>     * Turn mob stacking on
> 
>     * Allow mobs to stack
> 
>     * Turn mob stacking off
> 
>     * Attack a stacked mob until you kill it and see the death animation (example 4x Chicken)
> 
>     * mob will glitch and is now invincible (and it's still called 4x Chicken)
> 
> 
> I use WildStacker for item stacking and spawner stacking. So it bugs out in this situation. Invincible mobs cannot be killed with restarting, by using /butcher, or with the /kill command
> 
> Attached is a copy of my config file
> 
> [config.txt](https://github.com/OmerBenGera/WildStacker/files/6133899/config.txt)

Using /ws inspect, is the mob count going down?

**Comment by DarrienNN** [comment]
![image](https://user-images.githubusercontent.com/58543201/111033100-87757400-844a-11eb-8ca2-7492412669bf.png)
Hi there i also having the same issues

**Comment by YouSeeMeRunning2** [comment]
> ![image](https://user-images.githubusercontent.com/58543201/111033100-87757400-844a-11eb-8ca2-7492412669bf.png)
> Hi there i also having the same issues

He is using tuinity paper fork and the latest development build

**Comment by OmerBenGera** [comment]
Try using latest dev build, I think I found the issue.

**Comment by thecenters** [comment]
Confirming that this appears to be fixed in the latest dev build.

**Comment by OmerBenGera** [comment]
> 
> 
> Confirming that this appears to be fixed in the latest dev build.

Perfect. We'll wait for the others that commented to confirm it's fixed before I close this issue.
