### ISSUE TITLE
EntityDamageEvent damage on death

### ISSUE THREAD

**Issue by Insprill** [OmerBenGera/WildStacker#639]
### Minecraft's Version

Paper 1.19.2 build 201

### Plugin's Version

[2022.5 build 372](https://hub.bg-software.com/job/WildStacker/372/)

### Describe the bug

When handling entity deaths in `DeathSimulation`, the damage is fixed to 0. 

https://github.com/BG-Software-LLC/WildStacker/blob/f11c939a2985c5d562b2eab0f8f37f80b357164e/src/main/java/com/bgsoftware/wildstacker/utils/entity/logic/DeathSimulation.java#L83

Later, the event's damage is set to that result

https://github.com/BG-Software-LLC/WildStacker/blob/f11c939a2985c5d562b2eab0f8f37f80b357164e/src/main/java/com/bgsoftware/wildstacker/listeners/EntitiesListener.java#L255-L256

This causes issues with plugins that listen to the `EntityDamageEvent` on a higher priority because they can't get the damage dealt.

I'm not sure of a great way around this besides listening at a lower priority, however, that would cause issues with other plugins that modify the events damage on the `HIGHEST` priority, so input would be appreciated.

### To Reproduce

```java
public class TestPlugin extends JavaPlugin, Listener {
    @Override
    public void onEnable() {
        Bukkit.getPluginManager().registerEvents(this, this);
    }
    @EventHandler(priority = EventPriority.MONITOR)
    public void onDamage(EntityDamageEvent e) {
        System.out.println(e.getDamage());
    }
}
```
Kill a stacked entity, view the logged damage.

### Additional Information

Original issue reported to me: https://github.com/Insprill/damage-indicator/issues/9

**Comment by OmerBenGera** [comment]
Hey, thanks for reporting it.
Try using latest dev build, let me know if it's better.
The plugin now should fire a second event so other plugins can listen to the original event without having WS conflicting with it.
Let me know if it works now :)

**Comment by Insprill** [comment]
Build 374 partially fixes it, however, it looks like the secondary event only gets called after the entity has taken damage once, resetting each time an entity in the stack is killed.

**Comment by OmerBenGera** [comment]
> I tested it again with build 374, and that seems to solve the problem. However, the secondary event only gets called after the entity has taken damage once, resetting each time an entity in the stack is killed.

The event is called again when the first event is called.
I dont understand the problem

**Comment by Insprill** [comment]
Sorry, the first time a mob in a stack takes damage, both events are fired, but the second one still has a damage of zero. After that, all damage the mob takes fires the second event properly. Once it dies, assuming there are more in the stack, the process repeats. Here's an example with my plugin, with it not spawning indicators for 0 damage events.

https://user-images.githubusercontent.com/52843537/195102678-d8087218-08d7-4ea2-b583-4beccc3dfb3f.mp4

**Comment by OmerBenGera** [comment]
@Insprill There were errors in your dev build, which should be fixed now.
Try it again, let me know if it still occurs

**Comment by Insprill** [comment]
The issue still persists with build 375

**Comment by OmerBenGera** [comment]
@Insprill Should be fixed with latest dev build

**Comment by OmerBenGera** [comment]
> It seems to be fixed with build 376. Thank you!

Thanks for helping me with that :)
If there are new issues in the future, let me know by making new reports.
