### ISSUE TITLE
Cow / Sheep LAVA

### ISSUE THREAD

**Issue by YouSeeMeRunning2** [OmerBenGera/WildStacker#64]
![image](https://user-images.githubusercontent.com/61563491/109697451-21edd180-7b86-11eb-8fda-acc7bd5707dc.png)

I have a normal cow / sheep farm and the stack doesn't seem to be getting killed. They die one by one

**Comment by OmerBenGera** [comment]
Also, this place is for bug reports, not questions, so next time ask it on the discord server :)

**Comment by YouSeeMeRunning2** [comment]
The issue is that iron golems die in a stack by lava but cows and sheep don't. 

If I was to use fire_tick then players would be able to kill a full stack using fire aspect and I don't want that

**Comment by YouSeeMeRunning2** [comment]
After more investigating, I found that it's only iron golems that get killed as a stack when they die in lava. https://pastebin.com/GWtuuzgJ

**Comment by OmerBenGera** [comment]
Delete the sheep & cow rows (the last 4 rows).
Also, there's no way to only make them die by lava - when mobs are in lava, they can take damage by fire, fire_tick (not sure what the differences are) and lava damage. Therefore, you must list all of them.

**Comment by OmerBenGera** [comment]
Also, the instant kill doesn't mean that one hit from lava will kill them. It means that the entire stack will die when they die by lava

**Comment by YouSeeMeRunning2** [comment]
Iron golems stacks die at once when they die by lava (I'm not using FIRE_TICK). Not sure why the other mobs aren't.

**Comment by YouSeeMeRunning2** [comment]
https://gyazo.com/ef9df3652e0d6e0315878411ee1442b1

https://gyazo.com/d1d1766fe8f0dfbcafcbdfddc4cb981b

**Comment by OmerBenGera** [comment]
Iron Golems are 3 high tall, which means they are still touching the lava.
However, the other mobs don't take lava damage, and they are only taking damage by the fire tick after that.

**Comment by OmerBenGera** [comment]
If you put the lava one block higher, you'll see that iron golems don't die as well.

**Comment by YouSeeMeRunning2** [comment]
On 1.8 I used COW:FIRE 

What changed in 1.16?

**Comment by OmerBenGera** [comment]
idk xD
It's not something on my end tho - I only check for the last damage cause and check that

**Comment by YouSeeMeRunning2** [comment]
Fair enough. Thanks for the help

**Comment by OmerBenGera** [comment]
I'll check if I can somehow make it so it will still be considered as lava, even tho the real damage cause is fire.
If I manage to do so, you'll see a commit regarding this :)

**Comment by YouSeeMeRunning2** [comment]
Thank you :)
