### ISSUE TITLE
Errors with EpicSpawners

### ISSUE THREAD

**Issue by Leomelonseeds** [OmerBenGera/WildStacker#65]
Hello there,

Errors being spammed in console to do with EpicSpawners' API not being compatible, I think. Not sure when this error happens, but I'm assuming whenever a mob is spawned from a spawner.
![image](https://user-images.githubusercontent.com/17891302/110051250-58ecf000-7d0a-11eb-810f-a685fd3c7684.png)

EpicSpawners version: 7.0.7 (Latest)
WildStacker version: 3.5.1 b74 (Latest successful dev build)

Thanks in advance.

**Comment by OmerBenGera** [comment]
Are you sure you're using EpicSpawners 7? WildStacker detected EpicSpawners 6

**Comment by Leomelonseeds** [comment]
Yep, I'm very sure that I'm on the latest EpicSpawners version 7.0.7.

**Comment by OmerBenGera** [comment]
Whata your discord?

**Comment by OmerBenGera** [comment]
My bad, I thought there was support for EpicSpawners 7, but there wasn't.
I added support for it in the latest dev build :)
