### ISSUE TITLE
Problem with upgrade spawners and stacking.

### ISSUE THREAD

**Issue by Gohu1** [OmerBenGera/WildStacker#66]
Hi,

I asked for help on Discord but seems like my issue was not something known. I have some problems with stacking entities from upgraded spawners : they are not stacking. Even if mobs spawn from upgraded spawners by stacks, the stacks themselves are not stacking each other and it makes a lot of different stacks. But it works well with default spawners, mobs are stacked.

I tried everything : change the min-limit to 5, 2 or even 1. I did /ws simulate too, it displays that it's a success and different stacks could be stacked but they don't. I do not have limits to my stacks. I tried to enable/disable linked-entites. Nothing worked, so i suppose that the issue isn't coming from me or something i did.

**Comment by Gohu1** [comment]
![image](https://user-images.githubusercontent.com/79038599/110146619-12b39180-7ddb-11eb-9f42-aafaa84446ce.png)

**Comment by OmerBenGera** [comment]
Enable stack interval, let me know if it works

**Comment by Gohu1** [comment]
I already did, it didn't work too.

**Comment by OmerBenGera** [comment]
You probably didnt enable it correctly.
Show me your config

**Comment by Gohu1** [comment]
I tried different values : 0, 20, 200. Any of them was working. Helpers on discord already advised me to do this.

` # How much time should be passed between auto-stacking? (in ticks)
  # If you wish to disable the auto-stacking task, set the stack-interval to 0.
  stack-interval: 20`

**Comment by OmerBenGera** [comment]
Show me your entire config please. Upload it to pastebin

**Comment by Gohu1** [comment]
https://pastebin.com/U1YD9avu

Notice that i tried every single things i said in the first post. I reset the config several times too, it's why there's not much modifications in this one.

**Comment by OmerBenGera** [comment]
I thought you might have enabled stack-interval for items by a mistake, but you didn't.
Set the stack interval to 200 and make a restart to your server. If it doesn't work, then the simulate tool will not show SUCCESS.

**Comment by Gohu1** [comment]
Seems to work perfectly, i'll try with all the spawners upgrade/mobs to be sure but thanks for your help !

**Comment by OmerBenGera** [comment]
Ah, so the issue was probably because you didn't restart.
Due to some issues, you must restart when changing the stack interval.
If it works now as it should, just close the issue :)
