### ISSUE TITLE
Problems with killing fast feature.

### ISSUE THREAD

**Issue by Gohu1** [OmerBenGera/WildStacker#67]
Hi,

Sorry to bother again. It turns out that i can't kill entities fast with WildStacker. I tried to set `next-stack-knockback: false` but mobs continues to jump and down when i'm killing them. I know that there's a parameter which make them jump above 8cps clics, but i'm not clicking that fast.

**Comment by OmerBenGera** [comment]
I can't really control it, at least I don't think I can.
I will take another look at that, however I don't think I can really do anything with that :(

**Comment by OmerBenGera** [comment]
Hey, check out latest dev build, let me know if it helps

**Comment by Gohu1** [comment]
Yes, that's perfect !

**Comment by OmerBenGera** [comment]
Perfect :)
