### ISSUE TITLE
Issues with Slimefun and RedProtect

### ISSUE THREAD

**Issue by FauzanAlfansa** [OmerBenGera/WildStacker#69]
Non-trusted player can kill mobs in a RedProtect-claimed area with a Slimefun weapon but only if WildStacker is installed.

https://dl.dropboxusercontent.com/s/zsn3bdp1q8l9gws/javaw%202021-03-09%2016-22-36-27.mp4

Wildstacker version: b80

**Comment by OmerBenGera** [comment]
that might be because RedProtect or Slimefun cancel events in HIGHEST/HIGH priorities. They should use the correct priorities (NORMAL for this case). Nothing to be fixed on my end.
