### ISSUE TITLE
No Mob in Spawner

### ISSUE THREAD

**Issue by Darko266** [OmerBenGera/WildStacker#7]
When i place a spawner the spawner is empty but spawns the correct mob.
![slika](https://user-images.githubusercontent.com/20874142/103533736-f2745e80-4e8d-11eb-8649-1e09acc5ce31.png)

Im using WildStacker-b12.jar on PaperSpigot 1.12.2 build 1618 (latest 1.12.2)

**Comment by OmerBenGera** [comment]
Its not an issue of WildStacker... I am closing this for now
