### ISSUE TITLE
Item pickup not logged in CoreProtect

### ISSUE THREAD

**Issue by levtey** [OmerBenGera/WildStacker#70]
With build 81 and CoreProtect 19.4
Player item pickups are not logged in CoreProtect (with default WildStacker config)
I would assume this is because EntityPickupItemEvent is cancelled for stacked items.
![image](https://user-images.githubusercontent.com/60494179/110570622-0a28c700-810b-11eb-8321-245beb71b291.png)

**Comment by OmerBenGera** [comment]
I didn't know CoreProtect records such actions.
How can I see players picking up items without WildStacker? what's the command?

**Comment by levtey** [comment]
/co lookup (username) time:1h action:item should be sufficient

**Comment by OmerBenGera** [comment]
Fixed in latest dev build (82) :)
