### ISSUE TITLE
server crash

### ISSUE THREAD

**Issue by brasilcraft54** [OmerBenGera/WildStacker#72]
the minions of the jetminions plugin kill mobs and sometimes the server crashes because there are too many entities, I don't know how this is happening but it seems that the wildstacker is taking down too many entities.

https://prnt.sc/10ixda4
https://prnt.sc/10ixe8h

I went to the coordinates and found this
https://prnt.sc/10ixese

the server only didn't crash because I used farmlimiter to check what it was
https://prnt.sc/10ixfjk

the problem seems to be in the wildstacker it seems that the drops are not counting as 1 and as several

version wildstacker:  WildStacker-b82.jar
version server: 1.12.2 paper

plugins: https://prnt.sc/10ixk6b

**Comment by brasilcraft54** [comment]
when the chest is full the minion throws the items to the ground and this causes a bug with the wildstacker

https://prnt.sc/10ixw97
https://prnt.sc/10ixx0q

**Comment by OmerBenGera** [comment]
I don't understand how anything here is related to WildStacker
There aren't as many entities as it says there are....
