### ISSUE TITLE
The stack grows and decreases

### ISSUE THREAD

**Issue by Fredh1000** [OmerBenGera/WildStacker#739]
### Minecraft's Version

1.8.8 GuardSpigot

### Plugin's Version

Latest dev build: WildStacker build #411

### Describe the bug

Stacks instead of gradually increasing and growing in number, they grow and decrease.
There you can find a video that show you what i mean: https://www.youtube.com/watch?v=2ChrPlzkrSo

### To Reproduce

Wait for the spawner to spawn entities.

### Additional Information

A pastebin of my WildStacker config: https://pastebin.com/T3BheCDw

**Comment by OmerBenGera** [comment]
Run `/ws inspect` and give yourself the inspect tool.
Then, as soon as the stack amount decreases, right click on the entity, check if its actual stack amount is decreasing or only the hologram is wrong.

**Comment by Fredh1000** [comment]
I just tried. This isn't a problem related to holograms, this is a problem related to stack amount. When you moove an entire stack in an other chunk, the stack bugs and stops the normally growing entity number. 
Soon I will put the video link to better view the problem.

**Comment by Fredh1000** [comment]
The video: https://www.youtube.com/watch?v=pV-goY54pF4

**Comment by OmerBenGera** [comment]
Try it on Spigot/Paper, let me know if it works.

**Comment by Fredh1000** [comment]
In previous versions of the pl there was no such problem. I have no idea what version all this started from.

**Comment by OmerBenGera** [comment]
> In previous versions of the pl there was no such problem. I have no idea what version all this started from.

Try it with Paper/Spigot, let me know if it works.

**Comment by Fredh1000** [comment]
I've tried on paper and this bug still occur.

**Comment by OmerBenGera** [comment]
I can't seem to replicate the issue, so I must be doing something wrong
I placed 4 spawners of villagers next to each other, all maxed up to 25 in a stack and waited
It seems like the count for the villager still increases

**Comment by Fredh1000** [comment]
Move them to a different chunk than where the stack originated.

**Comment by OmerBenGera** [comment]
> Move them to a different chunk than where the stack originated.

I don't understand?

**Comment by Fredh1000** [comment]
If you move the mob stack to a different chunk than the chunk where the mob stack spawns, then the bug will start. It will also happen if the spwaners are in different chunks and from different chunks they spawn entities in a different chunk than the one they are placed in.

**Comment by OmerBenGera** [comment]
Can't seem to replicate the issue neither.
Do you mind taking another video of you actually moving the entities to another chunk and showing that it starts to occur afterwards?

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
I am closing this due to lack of response
If the issue still occurs let me know by replying here
