### ISSUE TITLE
AdvancedSpawners (Pickup)

### ISSUE THREAD

**Issue by YouSeeMeRunning2** [OmerBenGera/WildStacker#75]
When I pickup custom spawners form advancedspawners (Shift right click ) it gives me an egg spawner and leaves the model behind
![image](https://user-images.githubusercontent.com/61563491/111003803-b83ca700-837f-11eb-83ab-3190dc20cb5b.png)

**Comment by YouSeeMeRunning2** [comment]
Also unable to add spawners

**Comment by OmerBenGera** [comment]
Ahm how is it related to WildStacker..?

**Comment by YouSeeMeRunning2** [comment]
I'm using the wildstacker amount menu to pick the spawner up

**Comment by OmerBenGera** [comment]
> I'm using the wildstacker amount menu to pick the spawner up

Thats not supported unless they added support for it.
