### ISSUE TITLE
Place Permission Bug

### ISSUE THREAD

**Issue by nivcoo** [OmerBenGera/WildStacker#79]
Hello i use WildStacker-b84 in 1.12.2 i have activate the placed permission but i can place any spawner without permission wildstacker.place.*. Thx

**Comment by OmerBenGera** [comment]
Make sure you are not opped or have the wildstacker.* permission.
I will check the issue tomorrow and see if I can replicate it myself

**Comment by nivcoo** [comment]
Yes thx i have verified if i'm not opped and if the default group doesn't contain any wildstacker permission

**Comment by OmerBenGera** [comment]
By default, wildstacker.place.* is given to all players.
Did you revoke that permission from your players?

**Comment by nivcoo** [comment]
Yes it's that.... Why do add this permission by default if you have added an option to enable/disable the option ?

**Comment by OmerBenGera** [comment]
> 
> 
> Yes it's that.... Why do add this permission by default if you have added an option to enable/disable the option ?

It was requested a while ago, before the option to toggle it.
I will change it in next versions, as there's no need for it anymore.
