### ISSUE TITLE
Picked up items don't go back in off-hand slots

### ISSUE THREAD

**Issue by Gitberham** [OmerBenGera/WildStacker#8]
In normal Minecraft, picking up an item that you are currently only holding in your off-hand slot will return the items to that slot. However, with the installation of WildStacker, the item goes into a seperate inventory slot.

Video:
[https://www.youtube.com/watch?v=TsKRbffr-aQ](url)

**Comment by OmerBenGera** [comment]
This is intended, otherwise it will cause duplication glitches.
