### ISSUE TITLE
issue when droping items to any mobs

### ISSUE THREAD

**Issue by amarcais53** [OmerBenGera/WildStacker#80]
hello when im droping gold to piglin they are taking it into the wrong hand and not trading with me same with mobs when i drop armor they are taking it in the hand instead of geting it as armor my server is on hard so its not this im on wild stacker 3.5.1 and latest tuinity server and when i remove wildstacker everything works good there is my stacker config

**Comment by OmerBenGera** [comment]
Try latest dev build, its already fixed.
You can find it on https://bg-software.com/wildstacker/
