### ISSUE TITLE
items stacker work but only if items droped slowly

### ISSUE THREAD

**Issue by amarcais53** [OmerBenGera/WildStacker#81]
hello i made a quick video to show you the item stacker not working fine
if i drop items fast on the ground they dont get stacker but if i drop them slowly they dont
https://www.youtube.com/watch?v=j2IdfVK9RqQ

**Comment by amarcais53** [comment]
im on build 86

**Comment by amarcais53** [comment]
and latest tuinity 1.16.5

**Comment by OmerBenGera** [comment]
This is to prevent lag from checking nearby entities too often.
It caches the nearby entities for 5 seconds, so in this period of time new items are not counted.
This is intended :)

**Comment by amarcais53** [comment]
@OmerBenGera how can i counter it

**Comment by OmerBenGera** [comment]
> @OmerBenGera how can i counter it

What do you mean?

**Comment by amarcais53** [comment]
I mean how can I bypass this optimisation like can a chose how many second the server check to stack items

**Comment by OmerBenGera** [comment]
> 
> 
> I mean how can I bypass this optimisation like can a chose how many second the server check to stack items

no. I will try to fix this tho, therefore - I am reopening this.

**Comment by OmerBenGera** [comment]
Fixed in latest dev build :)
