### ISSUE TITLE
Baby variants of animals do not spawn wither roses.

### ISSUE THREAD

**Issue by monkeyno0dle** [OmerBenGera/WildStacker#82]
I have found that when the plugin is enabled the baby variants of animals do not drop wither roses upon death. I have tested this and made sure it is not a vanilla mechanic and that it is indeed cause by wildstacker.

**Comment by YouSeeMeRunning2** [comment]
Tested on 1.16.5 tunity vanilla and they dropped wither roses.
Tested on 1.16.5 tunity Wildstacker and they didn't drop wither roses


Spawn in a wither and then spawn in baby chickens with eggs

**Comment by OmerBenGera** [comment]
Add loot tables for babies and add wither roses to them.
I will add it as default for future versions

**Comment by OmerBenGera** [comment]
Fixed in latest dev build :)
