### ISSUE TITLE
EntityPickupItemEvent Pickup

### ISSUE THREAD

**Issue by YouSeeMeRunning2** [OmerBenGera/WildStacker#86]
https://pastebin.com/w9pYXmXj
1.8.8 Server Version

Coreproect can't be updated as the later versions don't support 1.8 

Currently Coreprotect version is 2.21.0

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it fixes the issue

**Comment by YouSeeMeRunning2** [comment]
Fized
