### ISSUE TITLE
Just some warnings. Are they harmful?

### ISSUE THREAD

**Issue by klaidoshka** [OmerBenGera/WildStacker#91]
**Minecraft's Version**
Paper 1.8.8

**Plugin's Version**: -
WildStacker 3.4.3 (a little outdated, but..)

**Describe the bug**
It's more a warning than a bug, but it is quite spammy sometimes. I have no "custom-items" plugins and console is talking about "CraftItem" sort of item, I have no clue... :| Can it even be harmful? If not, maybe I would be fine ignoring those warnings (x50/day at least)

**To Reproduce**
Have no clue, maybe someone is using some certain type of item, can't really possibly find out this.
Or... maybe... something wrong with my config?

**Additional information**
Warning: https://pastebin.com/GfzP6W4p

**Comment by OmerBenGera** [comment]
They are not harmful, but they might span your console.
I recommend updating to latest dev build
