### ISSUE TITLE
Stacked Mobs Causing Unreal Damage

### ISSUE THREAD

**Issue by Skizzles** [OmerBenGera/WildStacker#92]
**Minecraft's Version**
1.16.5

**Plugin's Version**: -
WildStacker-b95.jar

**Describe the bug**
All stacked mobs seem to be issuing larger damage than normal.

**To Reproduce**
Stack some mobs and let them hit you.

**Additional information**
Game Difficulty is on Normal, as you can see in the clip the stacked mobs from the spawner are issuing insane damage and even causing a one shot to players.
https://screenshots.skizzles.me/wAnA3/zejIlEMo96.mp4

**Comment by OmerBenGera** [comment]
WildStacker doesn't change the amount of damage that is dealt by stacked mobs.
Can you confirm it on a server with only WildStacker installed?

**Comment by Skizzles** [comment]
Looked into it more and found the cause closing this

**Comment by OmerBenGera** [comment]
What was the cause?

**Comment by Skizzles** [comment]
> What was the cause?

Found to be caused by a plugin registering attack damage of mobs incorrectly when stacked, was an incompatibility with Wildstacker that the other dev fixed.
