### ISSUE TITLE
Spawner Upgrade No Message Texts To Translate

### ISSUE THREAD

**Issue by Faceless0102** [OmerBenGera/WildStacker#95]
**Plugin's Version**: -
b96

**Describe the bug**
![image](https://user-images.githubusercontent.com/41546701/112474417-e2269e00-8d6f-11eb-9994-d5d07bb01176.png)
As you can see on the image, you can't translate the "Current Upgrade" or "Next Upgrade" message, can you make that available?

**Comment by OmerBenGera** [comment]
I know about it, its already suggested in the discussions section :)
